version: '3.8'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./www/darixanabot:/var/www/darixanabot
            - ./images/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "8000:80"
        container_name: darixanabot_nginx
        depends_on:
            - php
    php:
        build:
            context: .
            dockerfile: images/php/Dockerfile
        volumes:
            - ./www/darixanabot:/var/www/darixanabot
        depends_on:
            - mysql
        container_name: darixanabot_php
    mysql:
        image: mysql:8.2.0
        restart: always
        volumes:
            - ./mysql-data:/var/lib/mysql
        ports:
            - "3316:3306"
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --log_bin_trust_function_creators=1
        env_file:
            - images/mysql/mysql.env
        container_name: darixanabot_mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: darixanabot_pma
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - "8081:80"
